/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.infinispan.avro.client;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Request extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Request\",\"namespace\":\"org.infinispan.avro.client\",\"fields\":[{\"name\":\"jpqlString\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"schemaName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"startOffset\",\"type\":\"long\"},{\"name\":\"maxResult\",\"type\":\"int\"},{\"name\":\"local\",\"type\":\"boolean\",\"default\":\"true\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String jpqlString;
  @Deprecated public java.lang.String schemaName;
  @Deprecated public long startOffset;
  @Deprecated public int maxResult;
  @Deprecated public boolean local;

  /**
   * Default constructor.
   */
  public Request() {}

  /**
   * All-args constructor.
   */
  public Request(java.lang.String jpqlString, java.lang.String schemaName, java.lang.Long startOffset, java.lang.Integer maxResult, java.lang.Boolean local) {
    this.jpqlString = jpqlString;
    this.schemaName = schemaName;
    this.startOffset = startOffset;
    this.maxResult = maxResult;
    this.local = local;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return jpqlString;
    case 1: return schemaName;
    case 2: return startOffset;
    case 3: return maxResult;
    case 4: return local;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: jpqlString = (java.lang.String)value$; break;
    case 1: schemaName = (java.lang.String)value$; break;
    case 2: startOffset = (java.lang.Long)value$; break;
    case 3: maxResult = (java.lang.Integer)value$; break;
    case 4: local = (java.lang.Boolean)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'jpqlString' field.
   */
  public java.lang.String getJpqlString() {
    return jpqlString;
  }

  /**
   * Sets the value of the 'jpqlString' field.
   * @param value the value to set.
   */
  public void setJpqlString(java.lang.String value) {
    this.jpqlString = value;
  }

  /**
   * Gets the value of the 'schemaName' field.
   */
  public java.lang.String getSchemaName() {
    return schemaName;
  }

  /**
   * Sets the value of the 'schemaName' field.
   * @param value the value to set.
   */
  public void setSchemaName(java.lang.String value) {
    this.schemaName = value;
  }

  /**
   * Gets the value of the 'startOffset' field.
   */
  public java.lang.Long getStartOffset() {
    return startOffset;
  }

  /**
   * Sets the value of the 'startOffset' field.
   * @param value the value to set.
   */
  public void setStartOffset(java.lang.Long value) {
    this.startOffset = value;
  }

  /**
   * Gets the value of the 'maxResult' field.
   */
  public java.lang.Integer getMaxResult() {
    return maxResult;
  }

  /**
   * Sets the value of the 'maxResult' field.
   * @param value the value to set.
   */
  public void setMaxResult(java.lang.Integer value) {
    this.maxResult = value;
  }

  /**
   * Gets the value of the 'local' field.
   */
  public java.lang.Boolean getLocal() {
    return local;
  }

  /**
   * Sets the value of the 'local' field.
   * @param value the value to set.
   */
  public void setLocal(java.lang.Boolean value) {
    this.local = value;
  }

  /** Creates a new Request RecordBuilder */
  public static org.infinispan.avro.client.Request.Builder newBuilder() {
    return new org.infinispan.avro.client.Request.Builder();
  }
  
  /** Creates a new Request RecordBuilder by copying an existing Builder */
  public static org.infinispan.avro.client.Request.Builder newBuilder(org.infinispan.avro.client.Request.Builder other) {
    return new org.infinispan.avro.client.Request.Builder(other);
  }
  
  /** Creates a new Request RecordBuilder by copying an existing Request instance */
  public static org.infinispan.avro.client.Request.Builder newBuilder(org.infinispan.avro.client.Request other) {
    return new org.infinispan.avro.client.Request.Builder(other);
  }
  
  /**
   * RecordBuilder for Request instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Request>
    implements org.apache.avro.data.RecordBuilder<Request> {

    private java.lang.String jpqlString;
    private java.lang.String schemaName;
    private long startOffset;
    private int maxResult;
    private boolean local;

    /** Creates a new Builder */
    private Builder() {
      super(org.infinispan.avro.client.Request.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.infinispan.avro.client.Request.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing Request instance */
    private Builder(org.infinispan.avro.client.Request other) {
            super(org.infinispan.avro.client.Request.SCHEMA$);
      if (isValidValue(fields()[0], other.jpqlString)) {
        this.jpqlString = data().deepCopy(fields()[0].schema(), other.jpqlString);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.schemaName)) {
        this.schemaName = data().deepCopy(fields()[1].schema(), other.schemaName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.startOffset)) {
        this.startOffset = data().deepCopy(fields()[2].schema(), other.startOffset);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.maxResult)) {
        this.maxResult = data().deepCopy(fields()[3].schema(), other.maxResult);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.local)) {
        this.local = data().deepCopy(fields()[4].schema(), other.local);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'jpqlString' field */
    public java.lang.String getJpqlString() {
      return jpqlString;
    }
    
    /** Sets the value of the 'jpqlString' field */
    public org.infinispan.avro.client.Request.Builder setJpqlString(java.lang.String value) {
      validate(fields()[0], value);
      this.jpqlString = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'jpqlString' field has been set */
    public boolean hasJpqlString() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'jpqlString' field */
    public org.infinispan.avro.client.Request.Builder clearJpqlString() {
      jpqlString = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'schemaName' field */
    public java.lang.String getSchemaName() {
      return schemaName;
    }
    
    /** Sets the value of the 'schemaName' field */
    public org.infinispan.avro.client.Request.Builder setSchemaName(java.lang.String value) {
      validate(fields()[1], value);
      this.schemaName = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'schemaName' field has been set */
    public boolean hasSchemaName() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'schemaName' field */
    public org.infinispan.avro.client.Request.Builder clearSchemaName() {
      schemaName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'startOffset' field */
    public java.lang.Long getStartOffset() {
      return startOffset;
    }
    
    /** Sets the value of the 'startOffset' field */
    public org.infinispan.avro.client.Request.Builder setStartOffset(long value) {
      validate(fields()[2], value);
      this.startOffset = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'startOffset' field has been set */
    public boolean hasStartOffset() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'startOffset' field */
    public org.infinispan.avro.client.Request.Builder clearStartOffset() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'maxResult' field */
    public java.lang.Integer getMaxResult() {
      return maxResult;
    }
    
    /** Sets the value of the 'maxResult' field */
    public org.infinispan.avro.client.Request.Builder setMaxResult(int value) {
      validate(fields()[3], value);
      this.maxResult = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'maxResult' field has been set */
    public boolean hasMaxResult() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'maxResult' field */
    public org.infinispan.avro.client.Request.Builder clearMaxResult() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'local' field */
    public java.lang.Boolean getLocal() {
      return local;
    }
    
    /** Sets the value of the 'local' field */
    public org.infinispan.avro.client.Request.Builder setLocal(boolean value) {
      validate(fields()[4], value);
      this.local = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'local' field has been set */
    public boolean hasLocal() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'local' field */
    public org.infinispan.avro.client.Request.Builder clearLocal() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public Request build() {
      try {
        Request record = new Request();
        record.jpqlString = fieldSetFlags()[0] ? this.jpqlString : (java.lang.String) defaultValue(fields()[0]);
        record.schemaName = fieldSetFlags()[1] ? this.schemaName : (java.lang.String) defaultValue(fields()[1]);
        record.startOffset = fieldSetFlags()[2] ? this.startOffset : (java.lang.Long) defaultValue(fields()[2]);
        record.maxResult = fieldSetFlags()[3] ? this.maxResult : (java.lang.Integer) defaultValue(fields()[3]);
        record.local = fieldSetFlags()[4] ? this.local : (java.lang.Boolean) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
